name:                sprockell
version:             2022.0.0
github:              "bobismijnnaam/sprockell"
license:             MIT
author:              Jan Kuper, Martijn Bastiaan, Arjan Boeijink, Leon Schoorl, Bob Rubbens
maintainer:          "bobrubbens@gmail.com"
copyright:           "2022, University of Twente"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/bobismijnnaam/sprockell#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 0.6
- containers >= 0.5
- deepseq >= 1.4 && < 1.5
- network >= 2.6 && < 3.2

library:
  source-dirs: src

