import Sprockell

prog :: [Instruction]
prog = [ 
       Load (ImmValue 5) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 0), 
       Load (ImmValue 10) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 1), 
       Load (DirAddr 0) regA, 
       Push regA, 
       Load (DirAddr 1) regA, 
       Push regA, 
       Pop regB, 
       Pop regA, 
       Compute Add regA regB regA, 
       Push regA, 
       Pop regC, 
       Load (DirAddr 1) regA, 
       Push regA, 
       Pop regD, 
       Push regC, 
       Push regD, 
       Pop regB, 
       Pop regA, 
       Compute Gt regA regB regA, 
       Push regA, 
       Pop regA, 
       Compute Equal reg0 regA regA,
       Branch regA (Rel 6),
       Load (ImmValue 100) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 0), 
       Push regA, 
       Load (ImmValue 40) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 2), 
       Load (ImmValue 50) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 3), 
       Load (ImmValue 1) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 4), 
       Load (DirAddr 4) regA, 
       Push regA, 
       Pop regA, 
       Branch regA (Rel 7),
       Load (ImmValue 77) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 3), 
       Push regA, 
       Jump (Rel 6), 
       Load (ImmValue 66) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 2), 
       Push regA, 
       EndProg
       ]

main = run [prog]