import Sprockell

prog :: [Instruction]
prog = [
       Branch regSprID (Rel 28),
       Branch regSprID (Rel 10),
       Load (ImmValue 5) regA,
       Push regA,
       Pop regA,
       WriteInstr regA (DirAddr 4),
       WriteInstr regA (DirAddr 1),
       WriteInstr regA (DirAddr 2),
       WriteInstr regA (DirAddr 3),
       WriteInstr regA (DirAddr 4),
       Jump (Rel 35),
       ReadInstr (IndAddr regSprID),
       Receive regD,
       Compute Equal regD reg0 regE,
       Branch regD (Rel (-3)),
       ReadInstr (DirAddr 4),
       Receive regA,
       Push regA,
       Load (ImmValue 5) regA,
       Push regA,
       Pop regB,
       Pop regA,
       Compute Add regA regB regA,
       Push regA,
       Pop regA,
       WriteInstr regA (DirAddr 4),
       Push regA,
       Jump (Rel 18),
       ReadInstr (IndAddr regSprID),
       Receive regD,
       Compute Equal regD reg0 regE,
       Branch regD (Rel (-3)),
       ReadInstr (DirAddr 4),
       Receive regA,
       Push regA,
       Load (ImmValue 5) regA,
       Push regA,
       Pop regB,
       Pop regA,
       Compute Add regA regB regA,
       Push regA,
       Pop regA,
       WriteInstr regA (DirAddr 4),
       Push regA,
       Jump (Rel 1),
       EndProg
       ]

main =  runWithDebugger (debuggerSimplePrint myShow) [prog, prog, prog,prog,prog]